### ISSUE TITLE
Generate automatically the idx file with the TTD API

### ISSUE THREAD

**Issue by atxr** [airbus-cert/yara-ttd#11]
Currently, if the .idx file is missing when using heap mode 1, yara-ttd crashes with an error "index file missing, please regenerate it with WinDbg"
Instead of this error, yara-ttd should automatically generate this file thanks to the TTD API.

**Comment by ppxiaoxiao** [comment]
I need this feature too! 
I want to use TTD to automatically generate run files and then scan them with yara-ttd, 
but I get the same error message. 
This is really helpful, thanks! Keep it up!

**Comment by atxr** [comment]
Hi! Actually this is another issue, but I will work on it soon😉 
This one is about generating the `idx` files only from the `run` files.
The TTD API needs it to perform some operations, and currently if it's missing you need to open the run file inside windbg to generate it. I want to avoid this!
