### ISSUE TITLE
A question about slow scanning in full memory mode.

### ISSUE THREAD

**Issue by ppxiaoxiao** [airbus-cert/yara-ttd#6]
Thank you very much for your prompt reply!
May I ask you a question? 
Why is the full memory mode slow? 
Is it because Yara needs to scan the memory state of every instruction?

**Comment by atxr** [comment]
Hi! Sorry I might have closed your issue too quickly 😅 

Actually, the full memory mode calls `GetSystemInfo` from the Windows API which return a memory range for the process memory.
This range only specify the min and max address, even if there are huge chunks of memory which are not used within it. 
Most of the time, it's something like 0x1000 to 0x7fffffffffffff, which represents way too much memory to scan for yara and the TTD API in terms of performance.

> Is it because Yara needs to scan the memory state of every instruction?

Not necessarily,  it will only scan the time position that are specified in the parameters (see [time modes](https://github.com/airbus-cert/yara-ttd#time-modes)). But for each of these time positions, it will scan the whole range.

I hope this time my answer makes more sense!

**Comment by ppxiaoxiao** [comment]
Thank you so much! 
This helps a lot! It saved me a lot of time looking for these information. 
I'll come back for more help if I have any questions.
This project is amazing, keep up the good work! 
now，you can close my issue ::P

**Comment by atxr** [comment]
Thanks for the support and don't hesitate 😉
